# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 13:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectUser',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('permissions', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='subjectadmin',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='subjectadmin',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='subjecttags',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='subjecttags',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='admins',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='tags',
        ),
        migrations.AddField(
            model_name='tag',
            name='subject',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Subject'),
        ),
        migrations.DeleteModel(
            name='SubjectAdmin',
        ),
        migrations.DeleteModel(
            name='SubjectTags',
        ),
        migrations.AddField(
            model_name='subjectuser',
            name='subject',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='accounts.Subject'),
        ),
        migrations.AddField(
            model_name='subjectuser',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='subjects',
            field=models.ManyToManyField(
                through='accounts.SubjectUser', to='accounts.Subject'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
