# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170301_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subjectID',
            field=models.CharField(max_length=6, null=True, unique=True),
        ),
    ]
