# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 19:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170309_1914'),
        ('accounts', '0005_auto_20170309_1907'),
    ]

    operations = [
    ]
