# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 19:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20170309_1930'),
        ('accounts', '0006_auto_20170309_1937'),
    ]

    operations = [
    ]
