# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 08:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20170309_2041'),
        ('accounts', '0008_merge_20170309_1942'),
    ]

    operations = [
    ]
