# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 12:18
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_merge_20170313_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subjectID',
            field=models.CharField(default=accounts.models.random_id,
                                   max_length=6, null=True, unique=True),
        ),
    ]
