# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 18:29
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_merge_20170313_0932'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
            ],
        ),
        migrations.AlterField(
            model_name='lecture',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subjectID',
            field=models.CharField(default=accounts.models.random_id, max_length=6, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='rating',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='accounts.Rating'),
            preserve_default=False,
        ),
    ]
