# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 13:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_merge_20170320_1309'),
        ('accounts', '0011_auto_20170320_1240'),
    ]

    operations = [
    ]
