# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 09:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20170324_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagRating',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='tag',
            name='subject',
        ),
        migrations.AddField(
            model_name='tag',
            name='lecture',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Lecture'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='creator',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tagrating',
            name='tag',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='accounts.Tag'),
        ),
        migrations.AddField(
            model_name='tagrating',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile'),
        ),
    ]
