# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 10:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20170330_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
